# Generated by Django 2.2 on 2020-02-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('al_id', models.CharField(db_column='Al_id', max_length=4, primary_key=True, serialize=False)),
                ('al_desc_insumo', models.CharField(blank=True, db_column='Al_desc_insumo', max_length=45, null=True)),
                ('al_cant_insumo', models.IntegerField(blank=True, db_column='Al_cant_insumo', null=True)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('cod_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad_nombre', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cli_numdoc', models.CharField(db_column='Cli_numDoc', max_length=15, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(blank=True, db_column='Cli_nombre', max_length=45, null=True)),
                ('cli_apellido', models.CharField(blank=True, db_column='Cli_apellido', max_length=45, null=True)),
                ('cli_correo', models.CharField(blank=True, db_column='Cli_correo', max_length=45, null=True)),
                ('cli_telefono', models.IntegerField(blank=True, db_column='Cli_telefono', null=True)),
                ('cli_direccion', models.CharField(blank=True, db_column='Cli_direccion', max_length=45, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('consecutivo_id', models.CharField(db_column='Consecutivo_id', max_length=15, primary_key=True, serialize=False)),
                ('desc_factura', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormasPagos',
            fields=[
                ('fp_id', models.CharField(db_column='FP_id', max_length=3, primary_key=True, serialize=False)),
                ('fp_descripcion', models.CharField(blank=True, db_column='FP_descripcion', max_length=20, null=True)),
            ],
            options={
                'db_table': 'formas_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('insu_refer_id', models.CharField(db_column='Insu_refer_id', max_length=15, primary_key=True, serialize=False)),
                ('insu_nombre', models.CharField(blank=True, db_column='Insu_nombre', max_length=45, null=True)),
                ('insu_desc', models.CharField(blank=True, db_column='Insu_desc', max_length=45, null=True)),
                ('insu_precio', models.IntegerField(blank=True, db_column='Insu_precio', null=True)),
                ('insu_precio_iva', models.IntegerField(blank=True, db_column='Insu_precio_iva', null=True)),
                ('insu_cant_almacen', models.IntegerField(blank=True, db_column='Insu_cant_almacen', null=True)),
            ],
            options={
                'db_table': 'insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('cod_localidad', models.IntegerField(primary_key=True, serialize=False)),
                ('local_nombre', models.CharField(blank=True, db_column='Local_nombre', max_length=24, null=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenesFacturas',
            fields=[
                ('orden_compra', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc_compra', models.CharField(blank=True, max_length=45, null=True)),
                ('orden_fecha', models.DateField(blank=True, null=True)),
                ('orden_valor_total', models.IntegerField(blank=True, null=True)),
                ('orden_conse_factura', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'ordenes_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagosOrdenes',
            fields=[
                ('pg_orden_id', models.IntegerField(db_column='PG_orden_Id', primary_key=True, serialize=False)),
                ('pg_numero_cuotas', models.IntegerField(blank=True, db_column='PG_numero_cuotas', null=True)),
                ('pg_fecha', models.DateField(blank=True, db_column='PG_fecha', null=True)),
                ('pg_valor_total', models.IntegerField(blank=True, db_column='PG_valor_total', null=True)),
            ],
            options={
                'db_table': 'pagos_ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoInterno',
            fields=[
                ('pedint_id', models.CharField(db_column='pedInt_id', max_length=15, primary_key=True, serialize=False)),
                ('desc_pedido_interno', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pedido_interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('perf_id', models.CharField(db_column='Perf_id', max_length=3, primary_key=True, serialize=False)),
                ('perf_nombre', models.CharField(blank=True, db_column='Perf_nombre', max_length=10, null=True)),
                ('perf_desc', models.CharField(blank=True, db_column='Perf_desc', max_length=20, null=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('remision_id', models.CharField(db_column='Remision_id', max_length=15, primary_key=True, serialize=False)),
                ('desc_remision', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'remisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumentos',
            fields=[
                ('tipodoc_id', models.CharField(db_column='TipoDoc_id', max_length=2, primary_key=True, serialize=False)),
                ('tipodoc_desc', models.CharField(blank=True, db_column='TipoDoc_desc', max_length=24, null=True)),
            ],
            options={
                'db_table': 'tipodocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposInsumos',
            fields=[
                ('tpinsu_id', models.CharField(db_column='TpInsu_id', max_length=10, primary_key=True, serialize=False)),
                ('tpinsu_desc', models.CharField(blank=True, db_column='TpInsu_desc', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipos_insumos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_numdoc', models.CharField(db_column='Usu_numDoc', max_length=15, primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(blank=True, db_column='Usu_nombre', max_length=20, null=True)),
                ('usu_correo', models.CharField(blank=True, db_column='Usu_correo', max_length=15, null=True)),
                ('usu_password', models.CharField(blank=True, db_column='Usu_password', max_length=8, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturasInsumos',
            fields=[
                ('fac_orden_compra', models.ForeignKey(db_column='Fac_orden_compra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='places.OrdenesFacturas')),
                ('cant_vendidas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facturas_insumos',
                'managed': False,
            },
        ),
    ]
